### ISSUE TITLE
dkimSignMessage method declares Mimemessage return type but actually returns DkimMessage

### ISSUE THREAD

**Issue by saranyaelumalai-okta** [simple-java-mail/java-utils-mail-dkim#1]
In the example 
` private MimeMessage dkimSignMessage(MimeMessage message,  String signingDomain, String selector,  InputStream privateKeyStream)  throws Exception {`
        ` DkimSigner dkimSigner = new DkimSigner(signingDomain, selector, privateKeyStream );` 
        ` dkimSigner.setHeaderCanonicalization(Canonicalization.SIMPLE);` 
       `.....`
       ` return new DkimMessage(message, dkimSigner);`
    }`

dkimSignMessage method declares Mimemessage return type but actually returns DkimMessage. **Transport.send** allows only **MimeMessage** not DkimMessage which causes compatibility issue. Please guide.

**Comment by bbottema** [comment]
Please have a look at the inheritance chain. DkimMessage _is_ a MimeMessage and can be passed anywhere a MimeMessage can be passed. 

Perhaps you are using a Transport class from JavaMail, while the library depends on its successor Jakarta Mail?
